In [13]:
import pandas as pd

url = "https://projects.fivethirtyeight.com/nba-model/nba_elo_latest.csv"
df=pd.read_csv(url)
display(df.columns)

Index(['date', 'season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre',
       'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post',
       'carm-elo1_pre', 'carm-elo2_pre', 'carm-elo_prob1', 'carm-elo_prob2',
       'carm-elo1_post', 'carm-elo2_post', 'raptor1_pre', 'raptor2_pre',
       'raptor_prob1', 'raptor_prob2', 'score1', 'score2', 'quality',
       'importance', 'total_rating'],
      dtype='object')

In [14]:
display(df[df['date'] == '2022-11-18'])

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,...,carm-elo2_post,raptor1_pre,raptor2_pre,raptor_prob1,raptor_prob2,score1,score2,quality,importance,total_rating
223,2022-11-18,2023,0,NaN,WAS,MIA,1456.411746,1566.267296,0.485821,0.514179,...,NaN,1440.556082,1411.349721,0.642884,0.357116,NaN,NaN,23,38,31
224,2022-11-18,2023,0,NaN,PHI,MIL,1576.898839,1584.178136,0.630356,0.369644,...,NaN,1596.026086,1557.336947,0.657730,0.342270,NaN,NaN,79,14,47
225,2022-11-18,2023,0,NaN,CLE,CHO,1539.103911,1440.598152,0.758173,0.241827,...,NaN,1540.972935,1415.233297,0.762633,0.237367,NaN,NaN,41,30,36
226,2022-11-18,2023,0,NaN,MEM,OKC,1587.070853,1425.026692,0.818831,0.181169,...,NaN,1581.026532,1417.282328,0.798107,0.201893,NaN,NaN,48,5,27
227,2022-11-18,2023,0,NaN,HOU,IND,1348.821019,1453.513965,0.493247,0.506753,...,NaN,1298.661627,1480.856395,0.350526,0.649474,NaN,NaN,11,12,12
228,2022-11-18,2023,0,NaN,CHI,ORL,1455.408504,1365.228650,0.749278,0.250722,...,NaN,1483.288041,1339.048351,0.781009,0.218991,NaN,NaN,17,10,14
229,2022-11-18,2023,0,NaN,DAL,DEN,1564.282972,1551.550438,0.656772,0.343228,...,NaN,1628.433323,1422.994380,0.836596,0.163404,NaN,NaN,59,9,34
230,2022-11-18,2023,0,NaN,NOP,BOS,1569.949294,1686.397246,0.476347,0.523653,...,NaN,1567.779697,1683.906597,0.438231,0.561769,NaN,NaN,90,27,59
231,2022-11-18,2023,0,NaN,UTA,PHO,1569.276180,1603.719643,0.593240,0.406760,...,NaN,1549.461612,1584.912313,0.608219,0.391781,NaN,NaN,76,30,53
232,2022-11-18,2023,0,NaN,GSW,NYK,1586.621598,1511.033968,0.733170,0.266830,...,NaN,1580.712942,1513.313922,0.691153,0.308847,NaN,NaN,69,45,57
233,2022-11-18,2023,0,NaN,LAL,DET,1404.345291,1349.339327,0.709362,0.290638,...,NaN,1415.786346,1337.009251,0.757126,0.242874,NaN,NaN,9,1,5